spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/spring_batch
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 120000
      pool-name: batch-service
  # flyway configuration
  flyway:
    baselineOnMigrate: true
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:5432/spring_batch
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    open-in-view: false
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
server:
  port: 9191